apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-python-api
  template:
    metadata:
      labels:
        app: my-python-api
    spec:
      containers:
        - name: my-python-api-container
          image: uumar/python_api:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-python-api-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 80
  selector:
    app: my-python-api
